/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.table.DefaultTableModel;
import model.Fournisseur;
import model.Medicament;
import Service.FournisseurService;
import Service.MedicamentService;

/**
 *
 * @author PC
 */
public class MedicamentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form MedicamentForm
     */
    
    private MedicamentService ms;
    private FournisseurService fs;
    private DefaultTableModel model;
    private int selectedId = -1;

    
    public MedicamentForm() {
        initComponents();
        
    ms = new MedicamentService();
    fs = new FournisseurService();

    model = (DefaultTableModel) jTable1.getModel();

    loadFournisseurs();
    load();
    }
    void loadFournisseurs() {
    fournisseur.removeAllItems();
    fournisseur.addItem(new Fournisseur(0, "(Aucun)", "", ""));

    for (Fournisseur f : fs.listerTous()) {
        fournisseur.addItem(f);
    }
}

void load() {
    model.setRowCount(0);
    for (Medicament m : ms.listerTous()) {
        model.addRow(new Object[]{
            m.getId(),
            m.getNom(),
            m.getFamille(),
            m.getPrix(),
            m.getStock(),
            m.getSeuilAlerte(),
            m.getFournisseurId()
        });
    }
}

void clear() {
    nom.setText("");
    famille.setText("");
    prix.setText("");
    stock.setText("");
    seuil.setText("");
    fournisseur.setSelectedIndex(0);
    jTable1.clearSelection();
}

Medicament getFormData(int id) {
    String n = nom.getText().trim();
    String f = famille.getText().trim();

    if (n.isEmpty() || f.isEmpty())
        throw new IllegalArgumentException("Nom et Famille obligatoires");

    double p;
    int st;
    int se;

    try { p = Double.parseDouble(prix.getText().trim()); }
    catch (Exception e) { throw new IllegalArgumentException("Prix invalide"); }

    try { st = Integer.parseInt(stock.getText().trim()); }
    catch (Exception e) { throw new IllegalArgumentException("Stock invalide"); }

    try { se = Integer.parseInt(seuil.getText().trim()); }
    catch (Exception e) { throw new IllegalArgumentException("Seuil invalide"); }

    if (p < 0) throw new IllegalArgumentException("Prix doit être >= 0");
    if (st < 0) throw new IllegalArgumentException("Stock doit être >= 0");
    if (se < 0) throw new IllegalArgumentException("Seuil doit être >= 0");

    Fournisseur selected = (Fournisseur) fournisseur.getSelectedItem();
    Integer fid = (selected == null || selected.getId() == 0) ? null : selected.getId();

    return new Medicament(id, n, f, p, st, se, fid);
}

int getSelectedId() {
    int row = jTable1.getSelectedRow();
    if (row < 0) return -1;
    return Integer.parseInt(model.getValueAt(row, 0).toString());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        seuil = new javax.swing.JTextField();
        famille = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        fournisseur = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Medicament");

        jLabel1.setText("Nom :");

        jLabel2.setText("Prix :");

        jLabel3.setText("Seuil Alert  :");

        jLabel4.setText("Famille :");

        jLabel5.setText("Stock :");

        jLabel6.setText("Fournisseur :");

        fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fournisseurActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        jButton4.setText("Rafraichir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rafraichirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(seuil, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(prix)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1)
                        .addGap(382, 382, 382)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(130, 130, 130)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(famille)
                        .addComponent(stock)
                        .addComponent(fournisseur, 0, 249, Short.MAX_VALUE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(seuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Famille", "Prix", "Stock", "Seuil", "FournisseurID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        try {
        Medicament m = getFormData(0);
        ms.ajouter(m);
        load();
        clear();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
         if (selectedId == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sélectionne une ligne d'abord !");
        return;
    }

    try {
    Medicament m = new Medicament();
    m.setId(selectedId);
    m.setNom(nom.getText().trim());
    m.setFamille(famille.getText().trim());
    m.setPrix(Double.parseDouble(prix.getText().trim()));
    m.setStock(Integer.parseInt(stock.getText().trim()));
    m.setSeuilAlerte(Integer.parseInt(seuil.getText().trim()));

    Fournisseur selected = (Fournisseur) fournisseur.getSelectedItem();
    Integer fid = (selected == null || selected.getId() == 0) ? null : selected.getId();
    m.setFournisseurId(fid);

    boolean ok = ms.modifier(m);

    if (ok) {
        javax.swing.JOptionPane.showMessageDialog(this, "✅ Modifié avec succès");
        load();
        clear();
        selectedId = -1;
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "❌ Modification échouée");
    }

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erreur: " + e.getMessage());
}

    }//GEN-LAST:event_modifierActionPerformed

    private void rafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rafraichirActionPerformed
        // TODO add your handling code here:
        loadFournisseurs();
            load();
            clear();

    }//GEN-LAST:event_rafraichirActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        try {
        int id = getSelectedId();
        if (id == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sélectionne un médicament");
            return;
        }
        int rep = javax.swing.JOptionPane.showConfirmDialog(this, "Supprimer ce médicament ?");
        if (rep == javax.swing.JOptionPane.YES_OPTION) {
            ms.supprimer(id);
            load();
            clear();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_supprimerActionPerformed

    private void fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fournisseurActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            int row = jTable1.getSelectedRow();
    if (row == -1) return;

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // 0 = colonne ID (la 1ère colonne)
    selectedId = Integer.parseInt(model.getValueAt(row, 0).toString());

    
    nom.setText(model.getValueAt(row, 1).toString());
    famille.setText(model.getValueAt(row, 2).toString());
    prix.setText(model.getValueAt(row, 3).toString());
    stock.setText(model.getValueAt(row, 4).toString());
    seuil.setText(model.getValueAt(row, 5).toString());
    // FournisseurID est colonne 6
Object fidObj = model.getValueAt(row, 6);
Integer fid = (fidObj == null) ? null : Integer.valueOf(fidObj.toString());

if (fid == null || fid == 0) {
    fournisseur.setSelectedIndex(0); 
} else {
    boolean found = false;
    for (int i = 0; i < fournisseur.getItemCount(); i++) {
        Fournisseur fo = (Fournisseur) fournisseur.getItemAt(i);
        if (fo != null && fo.getId() == fid) {
            fournisseur.setSelectedIndex(i);
            found = true;
            break;
        }
    }
    if (!found) fournisseur.setSelectedIndex(0);
}
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField famille;
    private javax.swing.JComboBox fournisseur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField seuil;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
